# NumPy

In [13]:
import numpy as np

#### Create a 2-dimensional array with the shape (3, 2). Fill it with random data.

In [12]:
arr = [[1, 6], [2, 3], [2, 3]]
x = np.array(arr)

In [9]:
print (x)
print ('Shape: ', x.shape)

[[1 6]
 [2 3]
 [2 3]]
Shape:  (3, 2)


#### Add 3.2 to every element in the array.

In [15]:
res = x * 3.2
print(res)

[[ 3.2 19.2]
 [ 6.4  9.6]
 [ 6.4  9.6]]


#### Create another 2d array of size (3,2) of all ones

In [25]:
size = (3,2)
allOnes = np.ones(size)
print(allOnes)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### Use numpy.dot to multiply the arrays together. What does it do? Check the numpy docs to find out.

In [33]:
# dot = np.dot(x, allOnes)
# print(dot)

##### Couldn't multiply together
The rows of the 'x' matrix  does not align with the columns of the 'allOnes' matrix 

## ====================================================

#### Use an array slice to get just the first row of the resultant array.

In [53]:
data = np.array([[11, 22, 33, 44, 55],
                 [20, 3, 12, 22, 10],
                 [30, 16, 8, 9, 55]])
    slice = data[:-2, :]
print(slice)

IndentationError: unexpected indent (<ipython-input-53-a5e42a131e62>, line 4)

In [52]:
sum = np.sum(slice)
print(sum)

<class 'slice'>
